import type { Caso } from './types';

export const caso2026014: Caso = {
  id: '2026-014',
  numero: '2026-014',
  titulo: 'Auditoria de Continuidad Operativa de TI',
  banco: 'Banco Cordillera S.A.',
  periodo: 'Q2 2026 - Abril a Junio 2026',
  fechaInicio: '2026-03-12',
  estado: 'en-curso',
  objetivo:
    'Evaluar la suficiencia y efectividad de los controles de gobierno, continuidad, respaldos, gestion de terceros y seguimiento de auditoria interna sobre los sistemas de informacion criticos de Banco Cordillera S.A.',
  alcance:
    'El alcance comprende planificacion y organizacion de TI, operaciones de TI, servicios contratados con terceros, rol de auditoria interna, continuidad operativa, respaldos, comite de TI, roles de continuidad e inventario de activos criticos. Periodo revisado: 1 de enero de 2025 al 25 de mayo de 2026.',
  metodologia:
    'La auditoria se ejecuto mediante relevamiento, revision documental, entrevistas, walkthroughs, pruebas de detalle, analisis de riesgos y contraste contra COBIT PO1, PO2, PO3, PO4, PO7 y ME2; COSO ambiente de control, evaluacion de riesgos, actividades de control, informacion y comunicacion, y supervision; y RGSI secciones 2, 6, 11 y 12.',

  auditores: [
    {
      id: 'AUD-01',
      nombre: 'Valentina Cruz',
      rol: 'Auditora Senior / Lider de Proyecto',
      email: 'v.cruz@auditoria.local',
    },
    {
      id: 'AUD-02',
      nombre: 'Felipe Morales',
      rol: 'Auditor de Sistemas',
      email: 'f.morales@auditoria.local',
    },
    {
      id: 'AUD-03',
      nombre: 'Andrea Riquelme',
      rol: 'Especialista en Riesgos TI',
      email: 'a.riquelme@auditoria.local',
    },
  ],

  evidencias: [
    {
      id: 'EVD-001',
      tipo: 'politica',
      titulo: 'Politica de Continuidad de Negocios v3.1',
      descripcion: 'Documento marco del BCP y DRP. Define objetivos de recuperacion, responsables y procedimientos de activacion.',
      fecha: '2025-08-14',
      fuente: 'Gerencia de Riesgos TI - Banco Cordillera',
      formato: 'PDF',
      paginas: 48,
      estadoRevision: 'revisado',
      criterios: ['COBIT-PO1', 'RGSI-S6'],
      hallazgos: ['H-001'],
      enTablero: true,
    },
    {
      id: 'EVD-002',
      tipo: 'registro-sistema',
      titulo: 'Log de ejecucion de respaldos enero 2025 - mayo 2026',
      descripcion: 'Registros de jobs de respaldo para core bancario, base de datos de clientes y plataforma transaccional.',
      fecha: '2026-05-20',
      fuente: 'Plataforma de monitoreo de respaldos',
      formato: 'CSV',
      estadoRevision: 'revisado',
      criterios: ['COBIT-PO2', 'RGSI-S6'],
      hallazgos: ['H-002'],
      enTablero: true,
    },
    {
      id: 'EVD-003',
      tipo: 'acta',
      titulo: 'Acta de Comite TI - Q3 2025',
      descripcion: 'Acta formalizada del Comite de Tecnologia. Incluye acuerdos de continuidad y pendientes de seguimiento.',
      fecha: '2025-09-30',
      fuente: 'Secretaria del Comite TI',
      formato: 'PDF',
      paginas: 6,
      estadoRevision: 'revisado',
      criterios: ['COBIT-PO4', 'COSO-INFORMACION-COMUNICACION', 'RGSI-S2'],
      hallazgos: ['H-001', 'H-004'],
      enTablero: true,
    },
    {
      id: 'EVD-004',
      tipo: 'acta',
      titulo: 'Minuta de Comite TI - Q4 2025 sin formalizar',
      descripcion: 'Borrador de minuta sin firmas ni aprobacion formal. No permite demostrar acuerdos ni seguimiento.',
      fecha: '2025-12-31',
      fuente: 'Secretaria del Comite TI',
      formato: 'PDF',
      paginas: 3,
      estadoRevision: 'observado',
      criterios: ['COBIT-PO4', 'COSO-INFORMACION-COMUNICACION', 'RGSI-S2'],
      hallazgos: ['H-004'],
      enTablero: true,
    },
    {
      id: 'EVD-005',
      tipo: 'contrato',
      titulo: 'Contrato de servicios cloud vigente',
      descripcion: 'Contrato marco con proveedor cloud para infraestructura critica. No incluye clausulas especificas de continuidad ni derecho de auditoria.',
      fecha: '2024-01-15',
      fuente: 'Gerencia de Contratos',
      formato: 'PDF',
      paginas: 34,
      estadoRevision: 'revisado',
      criterios: ['COBIT-PO3', 'RGSI-S11'],
      hallazgos: ['H-003'],
      enTablero: true,
    },
    {
      id: 'EVD-006',
      tipo: 'documento',
      titulo: 'Resultados de prueba de restauracion 2024',
      descripcion: 'Informe de la ultima prueba de restauracion parcial ejecutada antes del periodo auditado.',
      fecha: '2024-08-23',
      fuente: 'Equipo de Continuidad TI',
      formato: 'PDF',
      paginas: 12,
      estadoRevision: 'revisado',
      criterios: ['COBIT-ME2', 'RGSI-S6'],
      hallazgos: ['H-001', 'H-002'],
    },
    {
      id: 'EVD-007',
      tipo: 'documento',
      titulo: 'Organigrama y roles TI vigente',
      descripcion: 'Documento de roles de TI y continuidad. Presenta responsables que ya no ocupan cargos criticos.',
      fecha: '2024-11-30',
      fuente: 'Recursos Humanos / Gerencia TI',
      formato: 'PDF',
      paginas: 18,
      estadoRevision: 'observado',
      criterios: ['COBIT-PO7', 'COSO-AMBIENTE-CONTROL', 'RGSI-S2'],
      hallazgos: ['H-005'],
      enTablero: true,
    },
    {
      id: 'EVD-008',
      tipo: 'inventario',
      titulo: 'Inventario de activos TI criticos - Q1 2026',
      descripcion: 'Inventario de activos clasificados como criticos para la operacion. Incluye propietarios y fecha de ultima actualizacion.',
      fecha: '2026-03-31',
      fuente: 'Gerencia de TI',
      formato: 'XLSX',
      estadoRevision: 'observado',
      criterios: ['COBIT-PO2', 'COBIT-ME2', 'COSO-SUPERVISION'],
      hallazgos: ['H-006'],
      enTablero: true,
    },
    {
      id: 'EVD-009',
      tipo: 'captura',
      titulo: 'Capturas del panel de respaldos Veeam',
      descripcion: 'Capturas del panel de monitoreo que muestran finalizacion de jobs sin verificacion automatica de integridad.',
      fecha: '2026-04-29',
      fuente: 'Captura en sitio - Equipo auditor',
      formato: 'PNG',
      estadoRevision: 'revisado',
      criterios: ['COBIT-PO2', 'RGSI-S6'],
      hallazgos: ['H-002'],
      enTablero: true,
    },
    {
      id: 'EVD-010',
      tipo: 'entrevista',
      titulo: 'Entrevista con CIO',
      descripcion: 'Entrevista sobre gobierno TI, comite, continuidad, contratos cloud y planes de mejora.',
      fecha: '2026-03-27',
      fuente: 'Trabajo de campo',
      formato: 'PDF',
      paginas: 8,
      estadoRevision: 'revisado',
      criterios: ['COBIT-PO1', 'COBIT-PO4', 'RGSI-S2'],
      hallazgos: ['H-004'],
      enTablero: true,
    },
    {
      id: 'EVD-011',
      tipo: 'entrevista',
      titulo: 'Entrevista con Jefa de Continuidad',
      descripcion: 'La responsable confirma que no existen ejercicios integrales BCP ejecutados en 2025-2026.',
      fecha: '2026-04-10',
      fuente: 'Trabajo de campo',
      formato: 'PDF',
      paginas: 6,
      estadoRevision: 'revisado',
      criterios: ['COBIT-PO1', 'COBIT-PO7', 'RGSI-S6'],
      hallazgos: ['H-001', 'H-005'],
      enTablero: true,
    },
    {
      id: 'EVD-012',
      tipo: 'entrevista',
      titulo: 'Entrevista con representante del proveedor cloud',
      descripcion: 'El proveedor confirma que el contrato estandar no incluye SLA de continuidad ni notificacion especifica de incidentes.',
      fecha: '2026-04-15',
      fuente: 'Reunion remota',
      formato: 'PDF',
      paginas: 5,
      estadoRevision: 'revisado',
      criterios: ['COBIT-PO3', 'RGSI-S11'],
      hallazgos: ['H-003'],
      enTablero: true,
    },
    {
      id: 'EVD-013',
      tipo: 'ficha-prueba',
      titulo: 'Ficha de prueba - Walkthrough del BCP',
      descripcion: 'Prueba que recorre procedimientos del BCP y valida responsables, registros de ejercicios y aplicabilidad.',
      fecha: '2026-04-22',
      fuente: 'Equipo auditor',
      formato: 'PDF',
      paginas: 14,
      estadoRevision: 'revisado',
      criterios: ['COBIT-ME2', 'RGSI-S6'],
      hallazgos: ['H-001', 'H-005'],
      enTablero: true,
    },
    {
      id: 'EVD-014',
      tipo: 'ficha-prueba',
      titulo: 'Ficha de prueba - Integridad de respaldos',
      descripcion: 'Prueba de detalle sobre respaldo, monitoreo y restauracion. Confirma ausencia de verificacion de integridad.',
      fecha: '2026-04-29',
      fuente: 'Equipo auditor',
      formato: 'PDF',
      paginas: 10,
      estadoRevision: 'revisado',
      criterios: ['COBIT-ME2', 'RGSI-S6'],
      hallazgos: ['H-002'],
      enTablero: true,
    },
  ],

  hallazgos: [
    {
      id: 'H-001',
      numero: 'H-001',
      titulo: 'Plan de continuidad sin prueba integral vigente',
      severidad: 'critico',
      nivelRiesgo: 'alto',
      condicion:
        'El BCP vigente no registra una prueba integral durante 2025 ni entre enero y mayo de 2026. La ultima prueba documentada corresponde a agosto de 2024.',
      criterio:
        'COBIT PO1 y ME2 requieren planificacion, seguimiento y evaluacion de controles de continuidad. RGSI seccion 6 exige operar controles de continuidad probados y documentados.',
      causa:
        'No existe calendario formal de ejercicios aprobado por el Comite TI ni responsable con autoridad para exigir su ejecucion.',
      efecto:
        'El banco no puede demostrar que recuperara servicios criticos dentro de RTO/RPO comprometidos ante un incidente real.',
      conclusion:
        'El hallazgo se mantiene porque la evidencia documental y entrevistas demuestran ausencia de prueba integral vigente.',
      probabilidad: 4,
      impacto: 5,
      recomendacion:
        'Aprobar un calendario anual de ejercicios BCP, ejecutar una prueba integral, documentar resultados y reportar seguimiento trimestral al Comite TI.',
      respuestaBanco: null,
      estadoRespuesta: 'pendiente',
      criterios: ['COBIT-PO1', 'COBIT-ME2', 'RGSI-S6', 'COSO-SUPERVISION'],
      evidencias: ['EVD-001', 'EVD-003', 'EVD-006', 'EVD-011', 'EVD-013'],
      respuestasAuditado: [],
      procesoCobit: 'PO1 / ME2',
      componenteCoso: 'Supervision',
      seccionRgsi: 'Seccion 6',
      estado: 'pendiente-respuesta',
      fechaEmision: '2026-05-14',
    },
    {
      id: 'H-002',
      numero: 'H-002',
      titulo: 'Respaldos criticos sin verificacion automatica de integridad',
      severidad: 'critico',
      nivelRiesgo: 'alto',
      condicion:
        'Los logs y capturas revisadas muestran trabajos de respaldo con estado OK/Error, pero sin control automatizado que valide integridad del contenido respaldado.',
      criterio:
        'COBIT PO2 exige identificar informacion critica y proteger su integridad. RGSI seccion 6 exige controles operativos de respaldo y recuperacion verificables.',
      causa:
        'El procedimiento de respaldos no incorpora validacion automatica post-ejecucion ni responsable tecnico formal para el control.',
      efecto:
        'Existe riesgo de respaldos inutilizables o corruptos no detectados hasta el momento de una restauracion real.',
      conclusion:
        'El control de respaldo es incompleto porque solo valida ejecucion del job y no recuperabilidad de la informacion.',
      probabilidad: 4,
      impacto: 5,
      recomendacion:
        'Implementar verificacion automatica de integridad, alertas, pruebas mensuales de restauracion y reporte de excepciones a operaciones TI.',
      respuestaBanco:
        'El banco acepta el hallazgo e informa que iniciara un proyecto de mejora de respaldos durante Q3 2026.',
      estadoRespuesta: 'aceptada',
      criterios: ['COBIT-PO2', 'COBIT-ME2', 'RGSI-S6', 'COSO-ACTIVIDADES-CONTROL'],
      evidencias: ['EVD-002', 'EVD-006', 'EVD-009', 'EVD-014'],
      respuestasAuditado: ['RSP-002'],
      procesoCobit: 'PO2 / ME2',
      componenteCoso: 'Actividades de control',
      seccionRgsi: 'Seccion 6',
      estado: 'respondido',
      fechaEmision: '2026-05-14',
    },
    {
      id: 'H-003',
      numero: 'H-003',
      titulo: 'Contrato cloud sin clausulas suficientes de continuidad',
      severidad: 'critico',
      nivelRiesgo: 'alto',
      condicion:
        'El contrato con proveedor cloud no incluye SLA de continuidad, RTO/RPO, notificacion de incidentes ni derecho de auditoria especifico.',
      criterio:
        'COBIT PO3 requiere direccion tecnologica formal para plataformas criticas. RGSI seccion 11 exige gestionar servicios y contratos con terceros criticos.',
      causa:
        'La contratacion se realizo con condiciones estandar sin checklist normativo previo ni revision especializada de riesgos TI.',
      efecto:
        'El banco queda expuesto a interrupciones de servicios criticos sin garantias contractuales ni mecanismos de exigibilidad.',
      conclusion:
        'El hallazgo se sustenta porque el contrato y la entrevista al proveedor confirman la ausencia de clausulas clave.',
      probabilidad: 3,
      impacto: 5,
      recomendacion:
        'Negociar addendum contractual con SLA, continuidad, notificacion, derecho de auditoria y procedimiento de seguimiento del proveedor.',
      respuestaBanco: null,
      estadoRespuesta: 'pendiente',
      criterios: ['COBIT-PO3', 'RGSI-S11', 'COSO-EVALUACION-RIESGOS'],
      evidencias: ['EVD-005', 'EVD-012'],
      respuestasAuditado: [],
      procesoCobit: 'PO3',
      componenteCoso: 'Evaluacion de riesgos',
      seccionRgsi: 'Seccion 11',
      estado: 'pendiente-respuesta',
      fechaEmision: '2026-05-14',
    },
    {
      id: 'H-004',
      numero: 'H-004',
      titulo: 'Comite de TI con actas incompletas y acuerdos sin trazabilidad',
      severidad: 'medio',
      nivelRiesgo: 'medio',
      condicion:
        'No existen actas formalizadas de Q4 2025 y Q1 2026. Hay minutas informales sin firmas, responsables ni seguimiento de acuerdos.',
      criterio:
        'COBIT PO4 exige definir organizacion y relaciones de TI. COSO informacion y comunicacion requiere documentar informacion relevante de control. RGSI seccion 2 exige gobierno formal de TI.',
      causa:
        'La secretaria del Comite TI no tiene mecanismo de escalamiento ni plazo controlado para formalizar actas.',
      efecto:
        'Se pierde trazabilidad de decisiones de TI, acuerdos de continuidad y seguimiento de acciones correctivas.',
      conclusion:
        'La falta de actas formalizadas debilita la evidencia de gobierno y seguimiento del control interno de TI.',
      probabilidad: 3,
      impacto: 3,
      recomendacion:
        'Formalizar actas pendientes, definir secretario responsable, plazo maximo de cinco dias habiles y control de seguimiento de acuerdos.',
      respuestaBanco:
        'El banco acepta el hallazgo y designo un nuevo secretario permanente del Comite TI.',
      estadoRespuesta: 'aceptada',
      criterios: ['COBIT-PO4', 'COSO-INFORMACION-COMUNICACION', 'RGSI-S2'],
      evidencias: ['EVD-003', 'EVD-004', 'EVD-010'],
      respuestasAuditado: ['RSP-004'],
      procesoCobit: 'PO4',
      componenteCoso: 'Informacion y comunicacion',
      seccionRgsi: 'Seccion 2',
      estado: 'respondido',
      fechaEmision: '2026-05-14',
    },
    {
      id: 'H-005',
      numero: 'H-005',
      titulo: 'Roles de continuidad operativa desactualizados',
      severidad: 'medio',
      nivelRiesgo: 'medio',
      condicion:
        'El BCP asigna funciones criticas a personas que ya no ocupan esos cargos. El organigrama vigente no refleja responsables reales de continuidad.',
      criterio:
        'COBIT PO7 requiere administrar recursos humanos de TI y asignar competencias. COSO ambiente de control exige responsabilidades claras. RGSI seccion 2 exige organizacion y roles formales.',
      causa:
        'No existe integracion entre cambios de personal, RRHH y actualizacion automatica del BCP.',
      efecto:
        'Ante una contingencia, podria existir confusion sobre responsabilidades, cadena de mando y ejecucion de tareas de recuperacion.',
      conclusion:
        'El hallazgo se mantiene porque el walkthrough y entrevistas confirman responsables desactualizados.',
      probabilidad: 3,
      impacto: 4,
      recomendacion:
        'Actualizar roles del BCP, vincular cambios de personal con revision del plan y capacitar a responsables designados.',
      respuestaBanco: null,
      estadoRespuesta: 'pendiente',
      criterios: ['COBIT-PO7', 'COSO-AMBIENTE-CONTROL', 'RGSI-S2'],
      evidencias: ['EVD-007', 'EVD-011', 'EVD-013'],
      respuestasAuditado: [],
      procesoCobit: 'PO7',
      componenteCoso: 'Ambiente de control',
      seccionRgsi: 'Seccion 2',
      estado: 'pendiente-respuesta',
      fechaEmision: '2026-05-14',
    },
    {
      id: 'H-006',
      numero: 'H-006',
      titulo: 'Inventario de activos criticos parcialmente desactualizado',
      severidad: 'bajo',
      nivelRiesgo: 'bajo',
      condicion:
        'El inventario Q1 2026 presenta activos criticos con ultima actualizacion superior a 90 dias y cuatro activos sin actualizacion mayor a 180 dias.',
      criterio:
        'COBIT PO2 requiere mantener arquitectura e informacion critica identificada. COBIT ME2 y COSO supervision exigen seguimiento del control interno.',
      causa:
        'El mantenimiento del inventario es manual y no existen alertas por registros vencidos.',
      efecto:
        'Las decisiones de continuidad y recuperacion pueden basarse en informacion incompleta sobre activos criticos.',
      conclusion:
        'La deficiencia no compromete de inmediato la operacion, pero reduce confiabilidad para planificacion y recuperacion.',
      probabilidad: 2,
      impacto: 2,
      recomendacion:
        'Configurar alertas de actualizacion, definir responsable mensual y reportar cumplimiento del inventario al Comite TI.',
      respuestaBanco:
        'El banco informa que inicio la revision completa del inventario y evaluara alertas automaticas.',
      estadoRespuesta: 'parcial',
      criterios: ['COBIT-PO2', 'COBIT-ME2', 'COSO-SUPERVISION'],
      evidencias: ['EVD-008'],
      respuestasAuditado: ['RSP-006'],
      procesoCobit: 'PO2 / ME2',
      componenteCoso: 'Supervision',
      seccionRgsi: '',
      estado: 'respondido',
      fechaEmision: '2026-05-14',
    },
  ],

  respuestasAuditado: [
    {
      id: 'RSP-002',
      hallazgoId: 'H-002',
      fecha: '2026-05-21',
      postura: 'acepta',
      argumento:
        'Se reconoce que la plataforma valida finalizacion del job, pero no ejecuta verificacion automatica de integridad sobre el contenido respaldado.',
      evidenciaPresentada: 'Plan preliminar de mejora de respaldos Q3 2026.',
      comentarioAuditor:
        'La respuesta acepta la condicion, pero el hallazgo se mantiene hasta observar implementacion y prueba de restauracion.',
      decisionAuditor: 'mantener',
    },
    {
      id: 'RSP-004',
      hallazgoId: 'H-004',
      fecha: '2026-05-21',
      postura: 'acepta',
      argumento:
        'Se designo secretario permanente del Comite TI y se formalizaran las actas pendientes.',
      evidenciaPresentada: 'Memorando interno de designacion del secretario.',
      comentarioAuditor:
        'La accion propuesta es razonable. Debe verificarse la formalizacion efectiva de actas y seguimiento de acuerdos.',
      decisionAuditor: 'mantener',
    },
    {
      id: 'RSP-006',
      hallazgoId: 'H-006',
      fecha: '2026-05-21',
      postura: 'acepta-parcialmente',
      argumento:
        'El banco indica que los activos criticos principales estan identificados, aunque acepta retrasos de actualizacion.',
      evidenciaPresentada: 'Listado actualizado parcial de activos core.',
      comentarioAuditor:
        'La respuesta reduce parcialmente la incertidumbre, pero no demuestra control completo sobre todos los activos criticos.',
      decisionAuditor: 'mantener',
    },
  ],

  timeline: [
    {
      id: 'EVT-001',
      tipo: 'solicitud-info',
      fecha: '2026-03-12',
      titulo: 'Solicitud formal de información',
      descripcion: 'Se envió carta de inicio y requerimiento documental sobre planificación TI, continuidad, respaldos, contratos y auditoría interna.',
      hallazgosVinculados: [],
    },
    {
      id: 'EVT-002',
      tipo: 'recepcion-evidencia',
      fecha: '2026-03-19',
      titulo: 'Recepción documental inicial',
      descripcion: 'El banco entregó política BCP, organigrama TI e inventario de activos críticos.',
      evidenciasVinculadas: ['EVD-001', 'EVD-007', 'EVD-008'],
    },
    {
      id: 'EVT-003',
      tipo: 'entrevista',
      fecha: '2026-03-27',
      titulo: 'Entrevista con CIO',
      descripcion: 'Se relevó gobierno TI, comité, continuidad, contratos cloud y planes de mejora.',
      evidenciasVinculadas: ['EVD-010'],
    },
    {
      id: 'EVT-004',
      tipo: 'recepcion-evidencia',
      fecha: '2026-04-03',
      titulo: 'Recepción de logs, contrato y actas',
      descripcion: 'Se recibieron logs de respaldo, contrato cloud, actas Q3 y minuta Q4 del Comité TI.',
      evidenciasVinculadas: ['EVD-002', 'EVD-003', 'EVD-004', 'EVD-005'],
    },
    {
      id: 'EVT-005',
      tipo: 'entrevista',
      fecha: '2026-04-10',
      titulo: 'Entrevista con Jefa de Continuidad',
      descripcion: 'Se confirmó ausencia de ejercicios BCP integrales y roles desactualizados.',
      evidenciasVinculadas: ['EVD-011'],
    },
    {
      id: 'EVT-006',
      tipo: 'entrevista',
      fecha: '2026-04-15',
      titulo: 'Entrevista con proveedor cloud',
      descripcion: 'El proveedor confirmó que el contrato estándar no incluye cláusulas específicas de continuidad.',
      evidenciasVinculadas: ['EVD-012'],
    },
    {
      id: 'EVT-007',
      tipo: 'prueba-aplicada',
      fecha: '2026-04-22',
      titulo: 'Walkthrough del BCP',
      descripcion: 'Se aplicó ficha de prueba sobre procedimientos, responsables y evidencia de ejercicios.',
      evidenciasVinculadas: ['EVD-013'],
      hallazgosVinculados: ['H-001', 'H-005'],
    },
    {
      id: 'EVT-008',
      tipo: 'prueba-aplicada',
      fecha: '2026-04-29',
      titulo: 'Prueba de integridad de respaldos',
      descripcion: 'Se revisó proceso de respaldo y restauración, identificando ausencia de verificación automática.',
      evidenciasVinculadas: ['EVD-009', 'EVD-014'],
      hallazgosVinculados: ['H-002'],
    },
    {
      id: 'EVT-009',
      tipo: 'observacion-identificada',
      fecha: '2026-05-07',
      titulo: 'Observaciones preliminares consolidadas',
      descripcion: 'Se consolidaron observaciones sobre BCP, respaldos, contratos, comité, roles e inventario.',
      hallazgosVinculados: ['H-001', 'H-002', 'H-003', 'H-004', 'H-005', 'H-006'],
    },
    {
      id: 'EVT-010',
      tipo: 'hallazgo-emitido',
      fecha: '2026-05-14',
      titulo: 'Comunicación preliminar de hallazgos',
      descripcion: 'Se enviaron seis hallazgos preliminares al banco auditado para respuesta formal.',
      hallazgosVinculados: ['H-001', 'H-002', 'H-003', 'H-004', 'H-005', 'H-006'],
    },
    {
      id: 'EVT-011',
      tipo: 'respuesta-banco',
      fecha: '2026-05-21',
      titulo: 'Respuesta parcial del banco auditado',
      descripcion: 'El banco respondió los hallazgos H-002, H-004 y H-006. Permanecen pendientes H-001, H-003 y H-005.',
      hallazgosVinculados: ['H-002', 'H-004', 'H-006'],
      respuestasVinculadas: ['RSP-002', 'RSP-004', 'RSP-006'],
    },
    {
      id: 'EVT-012',
      tipo: 'cierre',
      fecha: '2026-05-25',
      titulo: 'Cierre del trabajo de campo',
      descripcion: 'Se cierra trabajo de campo con hallazgos pendientes de respuesta y recomendaciones para seguimiento.',
      hallazgosVinculados: ['H-001', 'H-003', 'H-005'],
    },
  ],

  nodosTablero: [
    { id: 'N-EVD-001', tipo: 'documento', titulo: 'Politica BCP', subtitulo: 'EVD-001', refId: 'EVD-001', x: 80, y: 100 },
    { id: 'N-EVD-007', tipo: 'documento', titulo: 'Roles TI', subtitulo: 'EVD-007', refId: 'EVD-007', x: 80, y: 260 },
    { id: 'N-EVD-008', tipo: 'documento', titulo: 'Inventario activos', subtitulo: 'EVD-008', refId: 'EVD-008', x: 80, y: 420 },
    { id: 'N-EVD-005', tipo: 'documento', titulo: 'Contrato cloud', subtitulo: 'EVD-005', refId: 'EVD-005', x: 80, y: 580 },
    { id: 'N-EVD-002', tipo: 'evidencia', titulo: 'Logs respaldos', subtitulo: 'EVD-002', refId: 'EVD-002', x: 80, y: 740 },
    { id: 'N-EVD-009', tipo: 'evidencia', titulo: 'Capturas Veeam', subtitulo: 'EVD-009', refId: 'EVD-009', x: 80, y: 900 },
    { id: 'N-EVD-003', tipo: 'documento', titulo: 'Acta Comite Q3', subtitulo: 'EVD-003', refId: 'EVD-003', x: 300, y: 100 },
    { id: 'N-EVD-004', tipo: 'documento', titulo: 'Minuta Q4', subtitulo: 'EVD-004', refId: 'EVD-004', x: 300, y: 260 },
    { id: 'N-EVD-010', tipo: 'entrevista', titulo: 'Entrevista CIO', subtitulo: 'EVD-010', refId: 'EVD-010', x: 300, y: 420 },
    { id: 'N-EVD-011', tipo: 'entrevista', titulo: 'Entrevista continuidad', subtitulo: 'EVD-011', refId: 'EVD-011', x: 300, y: 580 },
    { id: 'N-EVD-012', tipo: 'entrevista', titulo: 'Entrevista proveedor', subtitulo: 'EVD-012', refId: 'EVD-012', x: 300, y: 740 },
    { id: 'N-EVD-013', tipo: 'prueba', titulo: 'Walkthrough BCP', subtitulo: 'EVD-013', refId: 'EVD-013', x: 300, y: 900 },
    { id: 'N-EVD-014', tipo: 'prueba', titulo: 'Prueba respaldos', subtitulo: 'EVD-014', refId: 'EVD-014', x: 300, y: 1060 },
    { id: 'N-H-001', tipo: 'hallazgo', titulo: 'H-001: BCP no probado', subtitulo: 'Riesgo alto', refId: 'H-001', x: 620, y: 100, severidad: 'critico' },
    { id: 'N-H-002', tipo: 'hallazgo', titulo: 'H-002: Respaldos', subtitulo: 'Riesgo alto', refId: 'H-002', x: 620, y: 300, severidad: 'critico' },
    { id: 'N-H-003', tipo: 'hallazgo', titulo: 'H-003: Contrato cloud', subtitulo: 'Riesgo alto', refId: 'H-003', x: 620, y: 500, severidad: 'critico' },
    { id: 'N-H-004', tipo: 'hallazgo', titulo: 'H-004: Actas comite', subtitulo: 'Riesgo medio', refId: 'H-004', x: 620, y: 700, severidad: 'medio' },
    { id: 'N-H-005', tipo: 'hallazgo', titulo: 'H-005: Roles BCP', subtitulo: 'Riesgo medio', refId: 'H-005', x: 620, y: 900, severidad: 'medio' },
    { id: 'N-H-006', tipo: 'hallazgo', titulo: 'H-006: Inventario', subtitulo: 'Riesgo bajo', refId: 'H-006', x: 620, y: 1060, severidad: 'bajo' },
    { id: 'N-C-PO1', tipo: 'criterio', titulo: 'COBIT PO1', subtitulo: 'Plan estrategico TI', refId: 'COBIT-PO1', x: 900, y: 60 },
    { id: 'N-C-PO2', tipo: 'criterio', titulo: 'COBIT PO2', subtitulo: 'Arquitectura informacion', refId: 'COBIT-PO2', x: 900, y: 200 },
    { id: 'N-C-PO3', tipo: 'criterio', titulo: 'COBIT PO3', subtitulo: 'Direccion tecnologica', refId: 'COBIT-PO3', x: 900, y: 340 },
    { id: 'N-C-PO4', tipo: 'criterio', titulo: 'COBIT PO4', subtitulo: 'Organizacion TI', refId: 'COBIT-PO4', x: 900, y: 480 },
    { id: 'N-C-PO7', tipo: 'criterio', titulo: 'COBIT PO7', subtitulo: 'RRHH TI', refId: 'COBIT-PO7', x: 900, y: 620 },
    { id: 'N-C-ME2', tipo: 'criterio', titulo: 'COBIT ME2', subtitulo: 'Control interno', refId: 'COBIT-ME2', x: 900, y: 760 },
    { id: 'N-C-RGSI-S2', tipo: 'criterio', titulo: 'RGSI S2', subtitulo: 'Planificacion TI', refId: 'RGSI-S2', x: 900, y: 900 },
    { id: 'N-C-RGSI-S6', tipo: 'criterio', titulo: 'RGSI S6', subtitulo: 'Operaciones TI', refId: 'RGSI-S6', x: 900, y: 1040 },
    { id: 'N-C-RGSI-S11', tipo: 'criterio', titulo: 'RGSI S11', subtitulo: 'Terceros', refId: 'RGSI-S11', x: 900, y: 1180 },
    { id: 'N-R-002', tipo: 'respuesta', titulo: 'Respuesta H-002', subtitulo: 'Acepta', refId: 'RSP-002', x: 1140, y: 300 },
    { id: 'N-R-004', tipo: 'respuesta', titulo: 'Respuesta H-004', subtitulo: 'Acepta', refId: 'RSP-004', x: 1140, y: 700 },
    { id: 'N-R-006', tipo: 'respuesta', titulo: 'Respuesta H-006', subtitulo: 'Parcial', refId: 'RSP-006', x: 1140, y: 1060 },
  ],

  conexionesTablero: [
    { id: 'C-001', desde: 'N-EVD-001', hacia: 'N-H-001', etiqueta: 'respalda' },
    { id: 'C-002', desde: 'N-EVD-011', hacia: 'N-H-001', etiqueta: 'respalda' },
    { id: 'C-003', desde: 'N-EVD-013', hacia: 'N-H-001', etiqueta: 'origina' },
    { id: 'C-004', desde: 'N-H-001', hacia: 'N-C-PO1', etiqueta: 'relacionado con' },
    { id: 'C-005', desde: 'N-H-001', hacia: 'N-C-ME2', etiqueta: 'relacionado con' },
    { id: 'C-006', desde: 'N-H-001', hacia: 'N-C-RGSI-S6', etiqueta: 'incumple' },
    { id: 'C-007', desde: 'N-EVD-002', hacia: 'N-H-002', etiqueta: 'respalda' },
    { id: 'C-008', desde: 'N-EVD-009', hacia: 'N-H-002', etiqueta: 'respalda' },
    { id: 'C-009', desde: 'N-EVD-014', hacia: 'N-H-002', etiqueta: 'origina' },
    { id: 'C-010', desde: 'N-H-002', hacia: 'N-C-PO2', etiqueta: 'relacionado con' },
    { id: 'C-011', desde: 'N-H-002', hacia: 'N-C-RGSI-S6', etiqueta: 'incumple' },
    { id: 'C-012', desde: 'N-H-002', hacia: 'N-R-002', etiqueta: 'responde' },
    { id: 'C-013', desde: 'N-EVD-005', hacia: 'N-H-003', etiqueta: 'respalda' },
    { id: 'C-014', desde: 'N-EVD-012', hacia: 'N-H-003', etiqueta: 'respalda' },
    { id: 'C-015', desde: 'N-H-003', hacia: 'N-C-PO3', etiqueta: 'relacionado con' },
    { id: 'C-016', desde: 'N-H-003', hacia: 'N-C-RGSI-S11', etiqueta: 'incumple' },
    { id: 'C-017', desde: 'N-EVD-003', hacia: 'N-H-004', etiqueta: 'respalda' },
    { id: 'C-018', desde: 'N-EVD-004', hacia: 'N-H-004', etiqueta: 'contradice' },
    { id: 'C-019', desde: 'N-H-004', hacia: 'N-C-PO4', etiqueta: 'relacionado con' },
    { id: 'C-020', desde: 'N-H-004', hacia: 'N-C-RGSI-S2', etiqueta: 'incumple' },
    { id: 'C-021', desde: 'N-H-004', hacia: 'N-R-004', etiqueta: 'responde' },
    { id: 'C-022', desde: 'N-EVD-007', hacia: 'N-H-005', etiqueta: 'respalda' },
    { id: 'C-023', desde: 'N-EVD-013', hacia: 'N-H-005', etiqueta: 'origina' },
    { id: 'C-024', desde: 'N-H-005', hacia: 'N-C-PO7', etiqueta: 'relacionado con' },
    { id: 'C-025', desde: 'N-H-005', hacia: 'N-C-RGSI-S2', etiqueta: 'incumple' },
    { id: 'C-026', desde: 'N-EVD-008', hacia: 'N-H-006', etiqueta: 'respalda' },
    { id: 'C-027', desde: 'N-H-006', hacia: 'N-C-PO2', etiqueta: 'relacionado con' },
    { id: 'C-028', desde: 'N-H-006', hacia: 'N-C-ME2', etiqueta: 'requiere seguimiento' },
    { id: 'C-029', desde: 'N-H-006', hacia: 'N-R-006', etiqueta: 'responde' },
  ],
};

export const casosList = [caso2026014];

export function getCasoById(id: string): Caso | undefined {
  return casosList.find(c => c.id === id);
}

export function getHallazgoById(casoId: string, hallazgoId: string) {
  const caso = getCasoById(casoId);
  return caso?.hallazgos.find(h => h.id === hallazgoId);
}

export function getEvidenciaById(casoId: string, evidenciaId: string) {
  const caso = getCasoById(casoId);
  return caso?.evidencias.find(e => e.id === evidenciaId);
}
